### ISSUE TITLE
Add TableCorrelations tool

### ISSUE THREAD

**Issue by sgsinclair** [sgsinclair/trombone#4]
table=[existing table id]
verify=[boolean – just verify, id returns empty if not there]
input=[tsv data]
inputFormat=[tsv]
columnHeaders=boolean
rowHeaders=boolean
columns=[array of columns indices (numbers) or headers (strings)]

**Comment by ajmacdonald** [comment]
https://github.com/sgsinclair/trombone/commit/68dc10772a97923891690845f35c34815ff7dfbb
